### ISSUE TITLE
Dedicated graphics section was not working

### ISSUE THREAD

**Issue by bigbadmoshe** [farag2/PC-information#2]
$qwMemorySize = (Get-ItemProperty -Path "HKLM:\SYSTEM\ControlSet001\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}\0*" -Name HardwareInformation.qwMemorySize -ErrorAction SilentlyContinue)."HardwareInformation.qwMemorySize"

gave me results.

got it from here: https://superuser.com/questions/1352111/how-do-i-identify-the-amount-of-ram-on-a-video-card-gpu/1352112

**Comment by farag2** [comment]
Hm...

**Comment by farag2** [comment]
Could you provide a remote access to your PC to test? I sold my vcard...

**Comment by bigbadmoshe** [comment]
ok super strange now its working im no expert i was only trying to help out.

is it possible after running the command i changed its working?

**Comment by farag2** [comment]
Have no idea. Thats why I want to figuare out what it's going on.

**Comment by bigbadmoshe** [comment]
also this error "Get-ItemPropertyValue : Property HardwareInformation.qwMemorySize does not exist at path" is shown if error output is not ignored

**Comment by farag2** [comment]
Anyway I need to see. Its just an error for me...

**Comment by bigbadmoshe** [comment]
Another strange thing

BIOS
Manufacturer             Version
------------             -------
American Megatrends Inc. 1605

Motherboard
Manufacturer          Product
------------          -------
ASUSTeK COMPUTER INC. PRIME H270M-PLUS

CPU
Name                                    Cores L3, MB Threads
----                                    ----- ------ -------
Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz     4      8       8

RAM
Manufacturer PartNumber           Speed, MHz Capacity, GB
------------ ----------           ---------- ------------
Transcend    JM2666HLB-8G               2400            8
Transcend    JM2400HLB-8G               2400            8

Physical disks
Model                     Drive type Bus type            Size, GB
-----                     ---------- --------            --------
SanDisk SDSSDHII240G      SSD        RAID                  223.57
Msft Virtual Disk         SSD        File Backed Virtual        8
ST2000DL003-9VT166        HDD        RAID                 1863.02
Samsung SSD 860 EVO 250GB SSD        RAID                  232.89
ST4000DM000-1F2168        HDD        RAID                 3726.02

is the only thing shown not any video cards.

**Comment by farag2** [comment]
I've written everything before. If you want me to help, I need to see it by myself. Now we're reading tea leaves.
